### ISSUE TITLE
API document

### ISSUE THREAD

**Issue by chishengshih** [younger50/Wu-Monitoring-API#2]
We need to prepare the list of APIs to be implemented in this project. Please start from the last version and revise it.

**Comment by younger50** [comment]
Proposed document format are in wiki with sample API page layout

**Comment by chishengshih** [comment]
Yuan-Yang, 

The wiki is empty. Can you send me the link? 

Daniel
−−--------------------------------------------
Chi-Sheng (Daniel) Shih
NEWS Lab, National Taiwan University
E-Mail: cshih@csie.ntu.edu.tw

## Phone: +886-2-33664927 Fax: +886-2-33663778

**Comment by younger50** [comment]
Here is a like to wiki page with "CreateUser" as example:
https://github.com/younger50/Wu-Monitoring-API/wiki/API-Design
